---

# Main tasks file for openjdk-jdk role

- name: 'INIT | Manage variables to use for our target'
  import_tasks: "{{ role_path }}/tasks/manage_variables.yml"
  tags:
    - 'role::openjdk-jdk'
    - 'role::openjdk-jdk::init'
    - 'role::openjdk-jdk::install'


- name: 'INSTALL | Manage OS installation tasks'
  include_tasks: "{{ role_path }}/tasks/install_{{ ansible_os_family | lower }}.yml"
  tags:
    - 'role::openjdk-jdk'
    - 'role::openjdk-jdk::init'
    - 'role::openjdk-jdk::install'
